package m20.bgm.downloader.v4.component

object SettingsComponent {
    const val SETTINGS_AUTO_CHECK_UPDATE_KEY = "auto_check_update"
    const val SETTINGS_AUTO_CHECK_UPDATE_ENABLED_VALUE = "true"
    const val SETTINGS_AUTO_CHECK_UPDATE_DISABLED_VALUE = "false"
    const val SETTINGS_AUTO_CHECK_UPDATE_DEFAULT_VALUE = SETTINGS_AUTO_CHECK_UPDATE_ENABLED_VALUE
    const val SETTINGS_SAVE_SEARCH_HISTORY_KEY = "save_history"
    const val SETTINGS_SAVE_SEARCH_HISTORY_ENABLED_VALUE = "true"
    const val SETTINGS_SAVE_SEARCH_HISTORY_DISABLED_VALUE = "false"
    const val SETTINGS_SAVE_SEARCH_HISTORY_DEFAULT_VALUE =
        SETTINGS_SAVE_SEARCH_HISTORY_ENABLED_VALUE
}
